#!/bin/bash

# UI 関連のディレクトリ構造を作成するスクリプト
# プロジェクトのルートが現在のディレクトリにあり、web/pages/ などを作成します

# 作成するディレクトリのリスト
directories=(
  "web/_env"
  "web/app"
  "web/assets/styles"
  "web/components"
  "web/composables"
  "web/constants"
  "web/layouts"
  "web/pages"
  "web/pages/admin/auth/components"
  "web/pages/admin/auth/login"
  "web/pages/admin/auth/logout"
  "web/pages/admin/auth/password-init"
  "web/pages/admin/auth/password-reset"
  "web/pages/admin/settings"
  "web/pages/admin/settings/components"
  "web/pages/admin/user"
  "web/pages/admin/user/components"
  "web/pages/admin/user/upsert"
  "web/pages/admin/user/edit"
  "web/pages/admin/types"
  "web/pages/member/auth/login"
  "web/pages/member/auth/logout"
  "web/pages/member/auth/password-init"
  "web/pages/member/auth/password-reset"
  "web/pages/member/report"
  "web/pages/member/report/components"
  "web/pages/member/report/upsert"
  "web/pages/member/settings"
  "web/pages/member/settings/components"
  "web/pages/member/user"
  "web/pages/member/user/components"
  "web/pages/member/user/upsert"
  "web/pages/member/user/edit"
  "web/pages/member/types"
  "web/server/_docs"
  "web/server/api"
  "web/server/api/admin"
  "web/server/api/member"
  "web/server/config"
  "web/server/constants"
  "web/server/controllers"
  "web/server/controllers/admin"
  "web/server/controllers/member"
  "web/server/dtos"
  "web/server/dtos/admin"
  "web/server/dtos/member"
  "web/server/mappers"
  "web/server/mappers/admin"
  "web/server/mappers/member"
  "web/server/middlewares"
  "web/server/models"
  "web/server/models/admin"
  "web/server/models/member"
  "web/server/repositories"
  "web/server/services"
  "web/server/services/admin"
  "web/server/services/member"
  "web/server/validators"
  "web/server/validators/admin"
  "web/server/validators/member"
  "web/services"
  "web/types"
  "web/types/admin"
  "web/types/member"
  "web/utils"
)

# 配列内の各ディレクトリを作成し、.gitkeep を配置
for dir in "${directories[@]}"; do
  mkdir -p "$dir"
  touch "$dir/.gitkeep"
done

echo "指定されたディレクトリ構造と .gitkeep ファイルが作成されました。"

touch "web/.prettierrc"
touch "web/.prettierignore"
touch "web/_env/.env.local"
touch "web/_misc/dir-tree.txt"
touch "web/app/spa-loading-template.html"
touch "web/assets/styles/global.scss"
touch "web/components/BaseBody.vue"
touch "web/components/BaseFooter.vue"
touch "web/components/BaseHeader.vue"
touch "web/composables/useAuth.ts"
touch "web/composables/useToast.ts"
touch "web/composables/useEnv.ts"
touch "web/constants/uiMessages.ts"
touch "web/constants/errorMessages.ts"
touch "web/layouts/default.vue"
touch "web/layouts/AdminUnauthorized.vue"
touch "web/layouts/MemberUnauthorized.vue"
touch "web/pages/index.vue"
touch "web/pages/[...notFound].vue"
touch "web/pages/admin/auth/login/index.vue"
touch "web/pages/admin/auth/logout/index.vue"
touch "web/pages/admin/auth/password-init/index.vue"
touch "web/pages/admin/auth/password-reset/index.vue"
touch "web/pages/admin/settings/index.vue"
touch "web/pages/admin/user/index.vue"
touch "web/pages/admin/user/upsert/index.vue"
touch "web/pages/admin/user/edit/index.vue"
touch "web/pages/member/auth/login/index.vue"
touch "web/pages/member/auth/logout/index.vue"
touch "web/pages/member/auth/password-init/index.vue"
touch "web/pages/member/auth/password-reset/index.vue"
touch "web/pages/member/report/index.vue"
touch "web/pages/member/report/upsert/index.vue"
touch "web/pages/member/settings/index.vue"
touch "web/pages/member/user/index.vue"
touch "web/pages/member/user/upsert/index.vue"
touch "web/pages/member/user/edit/index.vue"
touch "web/server/config/database.ts"
touch "web/server/constants/errorMessages.ts"
touch "web/server/types/api-types.d.ts"
touch "web/server/utils/api-error.ts"
touch "web/server/utils/api-response.ts"
touch "web/server/utils/api-request.ts"
touch "web/server/utils/password.ts"
touch "web/server/utils/token.ts"
touch "web/server/utils/logger.ts"
touch "web/server/utils/validator.ts"
touch "web/server/utils/logger.ts"
touch "web/services/apiClient.ts"
touch "web/types/apiTypes.d.ts"
touch "web/types/errorTypes.d.ts"
touch "web/types/authTypes.d.ts"
touch "web/types/userTypes.d.ts"
touch "web/types/reportTypes.d.ts"
touch "web/types/settingTypes.d.ts"
